apiVersion: v1
kind: ConfigMap
metadata:
  name: gunicorn-config
  namespace: flask
data:
  gunicorn.config: |-
    workers = 4
    worker_class = 'gevent'
    bind = '0.0.0.0:5000'
    timeout = 60