apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      volumes:
        - name: gunicorn-configmap-volume
          configMap:
            name: gunicorn-config
      containers:
      - name: flask-app
        image: bravcoveoko/flask:latest
        ports:
        - containerPort: 5000