apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask
spec:
  type: NodePort
  clusterIP: 10.102.254.65
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30000